apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: vprofile
  labels:
    app: frontend
    tier: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      initContainers:
        - name: wait-for-backend
          image: busybox:1.36
          command:
            [
              "sh",
              "-c",
              "until nc -z backend 8080; do echo waiting for backend; sleep 3; done;",
            ]
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: vprofile
  labels:
    app: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      nodePort: {{ .Values.frontend.service.nodePort }}