#workflow name
name: CI Pipeline

# run after any push on the main branch
on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

# clone the repo into the runner
      - name: Checkout Repository
        uses: actions/checkout@v4

# set up JDK 17 for the build
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

#build the artifact using Maven
      - name: Build Maven Project
        run: |
          mvn clean install
      - name: SonarQube Scan
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=vprofile \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

# check the SonarQube report
      - name: Check Sonar Report 
        run: |
         find . -name report-task.txt
         ls -R target || true

# wait for the SonarQube Quality Gate result
#      - name: Wait for Quality Gate
#        uses: sonarsource/sonarqube-quality-gate-action@master
#        with:
#          scanMetadataReportFile: target/sonar/report-task.txt
#          pollingTimeoutSec: 300
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

# build the Docker image for the backend
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Backend Image
        run: |
          docker build \
          -f docker/back/Dockerfile \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/vprofile-back:${{ github.sha }} \
          .

      - name: Build Frontend Image
        run: |
          docker build \
          -f docker/front/Dockerfile \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/vprofile-front:${{ github.sha }} \
          docker/front

      - name: Build Database Image
        run: |
          docker build \
          -f docker/db/Dockerfile \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/vprofile-db:${{ github.sha }} \
           docker/db


      - name: List Docker Images
        run: docker images

      - name: Scan Backend Image
        run: |
         docker run --rm \
         -v /var/run/docker.sock:/var/run/docker.sock \
         aquasec/trivy:latest image \
         --severity CRITICAL,HIGH \
         --exit-code 0 \
         ${{ secrets.DOCKERHUB_USERNAME }}/vprofile-back:${{ github.sha }}

      - name: Scan Frontend Image
        run: |
         docker run --rm \
         -v /var/run/docker.sock:/var/run/docker.sock \
         aquasec/trivy:latest image \
         --severity CRITICAL,HIGH \
         --exit-code 0 \
         ${{ secrets.DOCKERHUB_USERNAME }}/vprofile-front:${{ github.sha }}

      - name: Scan Database Image
        run: |
         docker run --rm \
         -v /var/run/docker.sock:/var/run/docker.sock \
         aquasec/trivy:latest image \
         --severity CRITICAL,HIGH \
         --exit-code 0 \
         ${{ secrets.DOCKERHUB_USERNAME }}/vprofile-db:${{ github.sha }}


      - name: Tag Backend as latest
        run: |
         docker tag \
         ${{ secrets.DOCKERHUB_USERNAME }}/vprofile-back:${{ github.sha }} \
         ${{ secrets.DOCKERHUB_USERNAME }}/vprofile-back:latest

      - name: Push Backend
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/vprofile-back:${{ github.sha }}

      - name: Tag Frontend as latest
        run: |
         docker tag \
         ${{ secrets.DOCKERHUB_USERNAME }}/vprofile-front:${{ github.sha }} \
         ${{ secrets.DOCKERHUB_USERNAME }}/vprofile-front:latest 

      - name: Push Frontend
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/vprofile-front:${{ github.sha }}

      - name: Tag Database as latest
        run: |
         docker tag \
         ${{ secrets.DOCKERHUB_USERNAME }}/vprofile-db:${{ github.sha }} \
         ${{ secrets.DOCKERHUB_USERNAME }}/vprofile-db:latest

      - name: Push Database
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/vprofile-db:${{ github.sha }}